spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_bot
spring.datasource.username=postgres
spring.datasource.password=chocolatefrog
telegram.bot.token=7750066877:AAGX6GwUmzyTcVmBnawwcBnBwyO27o-GQKg
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
spring.jpa.show-sql=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
